// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreSpaceApi.Data;

namespace NetCoreSpaceApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200507021050_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("NetCoreSpaceApi.Repositories.Entities.Comet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Comet");
                });

            modelBuilder.Entity("NetCoreSpaceApi.Repositories.Entities.Constelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Constelation");
                });

            modelBuilder.Entity("NetCoreSpaceApi.Repositories.Entities.Exoplanet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Distance")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Eponyn")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Mass")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("PerioDays")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Star")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("YearDiscover")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Exoplanet");
                });

            modelBuilder.Entity("NetCoreSpaceApi.Repositories.Entities.Galaxy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Constelation")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("OriginName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Galaxy");
                });

            modelBuilder.Entity("NetCoreSpaceApi.Repositories.Entities.Moon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Numeral")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Parent")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RadiusKm")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("YearDiscover");

                    b.HasKey("Id");

                    b.ToTable("Moon");
                });

            modelBuilder.Entity("NetCoreSpaceApi.Repositories.Entities.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("DiameterKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MassKg")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Moons");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SizeRelative")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SunDistance")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Planet");
                });

            modelBuilder.Entity("NetCoreSpaceApi.Repositories.Entities.Star", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ApparentMo")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Constelation")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Mass")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RightType")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SpectralGyr")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Star");
                });
#pragma warning restore 612, 618
        }
    }
}
